apiVersion: v1
kind: Service
metadata:
  name: api-mock-service
spec:
  type: NodePort
  selector:
    app: api-mock
  ports:
  - port: 4000
    targetPort: 4000
    nodePort: 32767

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-mock-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-mock
  template:
    metadata:
      labels:
        app: api-mock
    spec:
      imagePullSecrets:
        - name: aliyun
      containers:
        - name: api-mock
          image: registry.cn-shanghai.aliyuncs.com/attonex/api-mock-service:latest
          resources:
            limits:
              memory: "64Mi"
              cpu: "200m"
          ports:
          - containerPort: 4000
        

